version: '2'

services:
  database:
    container_name: djangodb
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
        MYSQL_DATABASE: 'djangoDB'
        MYSQL_USER: 'django'
        MYSQL_PASSWORD: 'password'

  djangoapp: 
    container_name: djangoapp
    image: djangoapp
    build: .
    volumes:
      - .:/src
    networks:
      - main_network
    depends_on:
      - database

        
networks:
  main_network:
    driver: bridge
